spring:
  datasource:
    name: syncDate
    url: jdbc:mysql://${db_host:47.100.55.164}:${db_port:3306}/${db_name:weixin}?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&maxAllowedPacket=67108864
    username: root
    password: qhh921114
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: config,slf4j,stat
      maxActive: 30
      initialSize: 2
      maxWait: 60000
      minIdle: 2
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      connectionInitSqls: set names utf8mb4;
  redis:
    database: 0
    host: 47.100.55.164
    port: 6379
    password:
    timeout: 1000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

weixin:
  token: qhh
  appId: wx795782ee6a732f14
  appsecret: de110a15cbcb00894f2df45b8f302e63
  accessUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  uploadUrl: https://api.weixin.qq.com/cgi-bin/media/upload?access_token=ACCESS_TOKEN&type=TYPE
  menuUrl: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
  menuDeleteUrl: https://api.weixin.qq.com/cgi-bin/menu/delete?access_token=ACCESS_TOKEN
